const data = [
  {
    taskId: 1,
    project: "Project Alpha",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 2,
    project: "Project Beta",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 3,
    project: "Project Gamma",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 4,
    project: "Project Alpha",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 5,
    project: "Project Beta",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 6,
    project: "Project Gamma",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 7,
    project: "Project Alpha",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 8,
    project: "Project Beta",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 9,
    project: "Project Gamma",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 10,
    project: "Project Alpha",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 11,
    project: "Project Beta",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 12,
    project: "Project Gamma",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 13,
    project: "Project Alpha",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 14,
    project: "Project Beta",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 15,
    project: "Project Gamma",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 16,
    project: "Project Alpha",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 17,
    project: "Project Beta",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 18,
    project: "Project Gamma",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 19,
    project: "Project Alpha",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 20,
    project: "Project Beta",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 21,
    project: "Project Gamma",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 22,
    project: "Project Alpha",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 23,
    project: "Project Beta",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 24,
    project: "Project Gamma",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 25,
    project: "Project Alpha",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 26,
    project: "Project Beta",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 27,
    project: "Project Gamma",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 28,
    project: "Project Alpha",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 29,
    project: "Project Beta",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 30,
    project: "Project Gamma",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 31,
    project: "Project Alpha",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 32,
    project: "Project Beta",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 33,
    project: "Project Gamma",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 34,
    project: "Project Alpha",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 35,
    project: "Project Beta",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 36,
    project: "Project Gamma",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 37,
    project: "Project Alpha",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 38,
    project: "Project Beta",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 39,
    project: "Project Gamma",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 40,
    project: "Project Alpha",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 41,
    project: "Project Beta",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 42,
    project: "Project Gamma",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 43,
    project: "Project Alpha",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 44,
    project: "Project Beta",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 45,
    project: "Project Gamma",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 46,
    project: "Project Alpha",
    task: "Design UI",
    teamMember: "Alice",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 47,
    project: "Project Beta",
    task: "Develop Backend",
    teamMember: "Bob",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
  {
    taskId: 48,
    project: "Project Gamma",
    task: "Set up Database",
    teamMember: "Charlie",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 100,
    status: "Completed",
  },
  {
    taskId: 49,
    project: "Project Alpha",
    task: "API Integration",
    teamMember: "Diana",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 60,
    status: "In Progress",
  },
  {
    taskId: 50,
    project: "Project Beta",
    task: "Deployment",
    teamMember: "Ethan",
    startDate: "2025-01-01",
    endDate: "2025-01-15",
    progress: 20,
    status: "Not Started",
  },
];

export default data;
